# Configuration Settings for C94-M8P device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

save:
  mask: 3103                # Save I/O, Message, INF Message, Nav, Receiver 
                            # Manager, Antenna, and Logging Configuration
  device: 4                 # Save to EEPROM

device: /dev/ttyACM0
frame_id: imu0

# Example calibration of an IMU:
#esf:
#  calibration:
#    linear_acceleration:
#      x_offset: 0.5
#      x_scale: 1.011
#      y_offset: 0.15
#      y_scale: 1.006
#      z_offset: -0.25
#      z_scale: 0.986

rate: 1                     # in Hz
nav_rate: 1                 # [# of measurement cycles], recommended 1 Hz, may 

hnr_rate: 10                # be either 5 Hz (Dual constellation) or 
                            # 8 Hz (GPS only)

tp:                         # Time Pulse
  freq: 2                   # Hz

dynamic_model: airborne2    # Airborne < 2G, 2D fix not supported (3D only), 
                            # Max Alt: 50km
                            # Max Horizontal Velocity: 250 m/s, 
                            # Max Vertical Velocity: 100 m/s
fix_mode: 3d

#enable_ppp: true           # Not supported by C94-M8P
#dr_limit: 1
useAdr: true 

uart1:
  baudrate: 115200           # C94-M8P specific
  in: 7
  out: 7
gnss:
  glonass: true             # Supported by C94-M8P
  beidou: false             # Supported by C94-M8P
  qzss: false               # Supported by C94-M8P

dgnss_mode: 3               # Fixed mode

inf: 
  all: true                   # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  all: true
  esf:
    raw: true
    meas: true
  tim:
    tm2: true
  nav:
    clock: true
  rxm:
    rawx: true
    sfrbx: true
