obstacle_range: 8.0
raytrace_range: 10.0
max_obstacle_height: 1.0
min_obstacle_height: 0.05
footprint: [[-0.16, -0.165], [-0.16, 0.165], [0.16, 0.165], [0.16, -0.165]]
#robot_radius: 0.35
# inflation_radius: 0.18 #0.225
footprint_padding: 0.05
transform_tolerance: 1.0 #seconds
map_topic: map
map_type: costmap
subscribe_to_updates: true
# cost_scaling_factor: 50 #10.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
global_frame: map
robot_base_frame: base_link
always_send_full_costmap: true
inflater_layer:
  inflation_radius: 0.2
  cost_scaling_factor: 10.0
