local_costmap:
  update_frequency: 7
  publish_frequency: 7 #10.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  origin_x: -2
  origin_y: -2
  resolution: 0.05
  # transform_tolerance: 0.25
  # inflation_radius: 1.0